[General]

; How much radiation is inflicted in relation to damage dealt to the player.
; Eg. fRadMult = 0.75 | 20 Damage dealt -> 15 Radiation damage
fRadMul = 1

; Minimum radiation inflicted regardless of damage dealt to the player.
fRadMin = 1


[Creature]

; Enable/disable types of creatures from inflicting radiation.
bGhoul = 1
bCentaur = 1
bSuperMutant = 0
bSwampFolk = 0
bSporeCarrier = 1
bTrog = 1
bTunneler = 1
bAnt = 0
bBloatfly = 1
bCazador = 0
bMantis = 0
bRadroach = 1
bRadscorpion = 1
bBigHorner = 0
bBrahmin = 0
bDog = 0
bDeathclaw = 0
bGecko = 0
bGiantRat = 0
bMirelurk = 1
bMoleRat = 0
bYaoGuai = 0
